import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FirebaseClientProvider } from "@/firebase";
import { Toaster } from 'react-hot-toast';
import { LanguageProvider } from "@/i18n";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className="dark" suppressHydrationWarning>
      <body className={`${inter.className} bg-background`}>
        <div className="absolute top-0 left-0 w-full h-full z-0 overflow-hidden">
            <div className="absolute top-1/4 -left-32 w-96 h-96 bg-primary/10 rounded-full filter blur-3xl animate-blob opacity-50"></div>
            <div className="absolute bottom-1/4 -right-32 w-96 h-96 bg-secondary/10 rounded-full filter blur-3xl animate-blob animation-delay-2000 opacity-50"></div>
        </div>
        <div className="relative z-10">
          <LanguageProvider>
            <FirebaseClientProvider>
              {children}
              <Toaster 
                position="top-right"
                toastOptions={{
                  style: {
                    background: 'hsl(var(--background))',
                    color: 'hsl(var(--foreground))',
                    border: '1px solid hsl(var(--border))',
                  },
                  success: {
                    iconTheme: {
                      primary: 'hsl(var(--primary))',
                      secondary: 'hsl(var(--background))',
                    },
                  },
                  error: {
                    iconTheme: {
                      primary: 'hsl(var(--destructive))',
                      secondary: 'hsl(var(--foreground))',
                    },
                  },
                }}
              />
              </FirebaseClientProvider>
          </LanguageProvider>
        </div>
      </body>
    </html>
  );
}
